CREATE OR REPLACE FUNCTION if_exists_examples()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $trg$
DECLARE
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF NOT EXISTS(SELECT 1 FROM TAB1) THEN
            RETURN a;
        END IF;
        DROP TABLE IF EXISTS TAB2;
        CREATE SCHEMA IF NOT EXISTS sch1;
        IF (a IS NOT NULL) THEN
            RETURN a;
        END IF;
    END IF;
    RETURN a;
END;
$trg$;
